name: Build & Test

on:
  push:
    branches: [cobalt]
  pull_request:
    branches: [cobalt]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - run: npm ci
      - run: npm run buildprod
      - run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: youtube_adfree_ipk
          path: |
            ${{github.workspace}}/youtube.leanback.v4_*_all.ipk
