name: Build & Release

on:
  push:
    branches:
      - '!*'
    tags:
      - 'v*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - run: npm ci
      - run: npm run buildprod
      - run: npm run package
      - run: npm run manifest

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: 'Release ${{ github.ref }}'
          prerelease: true
          draft: false
          allowUpdates: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          artifacts: '*.ipk,*.manifest.json'
